//------------------------------------------------------------------------------
// <auto-generated>
<<<<<<< HEAD
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
=======
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
>>>>>>> origin/master
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acceso_BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cocheras
    {
<<<<<<< HEAD
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
=======
>>>>>>> origin/master
        public Cocheras()
        {
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int IdCochera { get; set; }
        public int IdPropietario { get; set; }
        public string Ubicacion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFin { get; set; }
        public string Descripcion { get; set; }
        public decimal Latitud { get; set; }
        public decimal Longitud { get; set; }
        public int MetrosCuadrados { get; set; }
        public short TipoVehiculo { get; set; }
        public decimal Precio { get; set; }
        public string Imagen { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
<<<<<<< HEAD
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
=======
>>>>>>> origin/master
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
