//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlquilaCocheras.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class cochera
    {
        public cochera()
        {
            this.puntuacion = new HashSet<puntuacion>();
            this.reserva = new HashSet<reserva>();
            this.vehiculo_cochera = new HashSet<vehiculo_cochera>();
        }
    
        public int id_cochera { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<System.TimeSpan> hora_inicio { get; set; }
        public Nullable<System.TimeSpan> hora_fin { get; set; }
        public Nullable<int> metros_cuad { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<int> fk_ubicacion { get; set; }
        public Nullable<int> fk_usuario { get; set; }
        public string foto { get; set; }
    
        public virtual ubicacion ubicacion { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual ICollection<puntuacion> puntuacion { get; set; }
        public virtual ICollection<reserva> reserva { get; set; }
        public virtual ICollection<vehiculo_cochera> vehiculo_cochera { get; set; }
    }
}
