//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acceso_Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cocheraEntities : DbContext
    {
        public cocheraEntities()
            : base("name=cocheraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cochera> cochera { get; set; }
        public DbSet<puntuacion> puntuacion { get; set; }
        public DbSet<reserva> reserva { get; set; }
        public DbSet<ubicacion> ubicacion { get; set; }
        public DbSet<usuario> usuario { get; set; }
        public DbSet<vehiculo> vehiculo { get; set; }
        public DbSet<vehiculo_cochera> vehiculo_cochera { get; set; }
    }
}
