//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acceso_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class puntuacion
    {
        public int id_puntuacion { get; set; }
        public Nullable<int> puntuacion1 { get; set; }
        public Nullable<int> fk_usuario { get; set; }
        public Nullable<int> fk_cochera { get; set; }
    
        public virtual cochera cochera { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
