//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acceso_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicacion
    {
        public ubicacion()
        {
            this.cochera = new HashSet<cochera>();
            this.reserva = new HashSet<reserva>();
        }
    
        public int id_ubicacion { get; set; }
        public string descripcion { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
    
        public virtual ICollection<cochera> cochera { get; set; }
        public virtual ICollection<reserva> reserva { get; set; }
    }
}
