//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acceso_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculo
    {
        public vehiculo()
        {
            this.vehiculo_cochera = new HashSet<vehiculo_cochera>();
        }
    
        public int id_vehiculo { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<vehiculo_cochera> vehiculo_cochera { get; set; }
    }
}
