//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acceso_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculo_cochera
    {
        public int id_vehiculo_cochera { get; set; }
        public Nullable<int> fk_vehiculo { get; set; }
        public Nullable<int> fk_cochera { get; set; }
    
        public virtual cochera cochera { get; set; }
        public virtual vehiculo vehiculo { get; set; }
    }
}
